# DEPRECATED: 
#  - This file is no longer in use as of https://github.com/meta-pytorch/pytorch-gha-infra/pull/798.
#  - If you want to update what auto-scalable runners are available to the meta-pytorch org, please
#    update the global scale-config file at https://github.com/pytorch/test-infra/blob/main/.github/scale-config.yml
